@startuml nfproxydb


entity Service {
    *string **id** 
    --
    *string name
    *enum status (start/stop)
    *string proto (tcp/http)
    *int port
    *string ip_or_interface
}

entity PyFilter {
    *string **name**
    --
    *int blocked_packets
    *int edited_packets
    *string code??
}


PyFilter }o--|| Service : "works on"

@enduml